### ISSUE TITLE
Spider error processing

### ISSUE THREAD

**Issue by josediogonc** [leogregianin/tesouro-direto#2]
Hello,

I tried to run the application and got the error:

`2020-06-07 10:54:13 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.tesouro.fazenda.gov.br/tesouro-direto-precos-e-taxas-dos-titulos> (referer: None)
2020-06-07 10:54:13 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.tesouro.fazenda.gov.br/tesouro-direto-precos-e-taxas-dos-titulos> (referer: None)
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\tesourodiretoapp\tesouro-direto-master\tesourodireto\spiders\tesourodireto.py", line 17, in parse
    for index in xrange((len(list_resp)/5)):
NameError: name 'xrange' is not defined
2020-06-07 10:54:13 [scrapy.core.engine] INFO: Closing spider (finished)
2020-06-07 10:54:13 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 341,
`

**Comment by josediogonc** [comment]
I mada an update in tesourodireto.py and got it! :)
